name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
jobs:
  BuildSimulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Release Manager
        id: check_release_manager
        run: echo "Is Release Manager= ${{ github.actor == 'talorlik' }}"
      - name: Build
        if: steps.check_release_manager.outputs.is_release_manager == 'true'
        run: |
          echo Building and packing an app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        if: steps.check_release_manager.outputs.is_release_manager == 'true'
        run: |
          echo Deploying into Test env
 
